class Description {
  static var des =
      'As variáveis são elementos básicos na programação, pois são aquelas que armazenam os dados que precisamos no nosso algoritmo. Cada dado pode ser de um tipo diferente e, por isso precisamos mostrar ao nosso algoritmo logo no início o que esperar armazenar\n\n   •	int: Variável número do tipo inteiro, positivo ou negativo.\n   •	float: Variável numérica do tipo decimal.\n   •	double: Variável numérica do tipo decimal de precisão dupla.\n    •	char: Variável que representa um caractere do tipo texto.\n   •	string: Variável que representa um conjunto de caracteres do tipo texto.\n    •	boolean: Variável booleana, ou seja, que pode representar somente dois valores, verdadeiro ou falso.\n\nAo contrário das variáveis, que podemos alterar o valor conforme a necessidade do algoritmo a ser desenvolvido, as constantes precisam ser inicializadas e não podem ter o seu valor alterado.\n\n';

  static var des1 =
      "O tipo de dados primitivo mais simples é o chamado booleano ( ou lógico ). Pra quem não conhece esse tipo de dados, um dado booleano só pode assumir dois valores (VERDADEIRO ou FALSO) ou (True ou False). Também como operador lógico se utiliza o AND (como incremento), OU (como alternativa).\n\nSímbolo  	Operação  	Exemplo 	Descrição\nAND &&	  E	  n1 && n2	  Verdadeira se n1 e n2 forem verdadeiras\nOR ||	  OU	  n1 || n2	  Verdadeira se n1 ou n2 forem verdadeiras\n\nOs operadores aritméticos executam operações matemáticas, como adição e subtração, multiplicação, divisão, entre outras operações, fornecendo assim um resultado.\n\nExemplo:\n\nSímbolo	Operação	Exemplo	Descrição\n+	Adição	n1 + n2	Soma os dois valores\n-	Subtração	n1 - n2	Subtrai os dois valores\n*	Multiplicação	n1 * n2	Multiplica os dois valores\n/	Divisão	n1 / n2	Divide os dois valores\n\n";

  static var des2 =
      "A condicional IF é uma estrutura condicional que executa a afirmação, dentro do bloco, se determinada condição for verdadeira. Se for falsa, executa as afirmações dentro de ELSE.\nA instrução SWITCH é um tipo de mecanismo de controle de seleção usado para permitir que o valor de uma variável ou expressão mude o fluxo de controle da execução do programa via pesquisa e mapa.\n\n";

  static var des3 =
      "  WHILE:\n\nA instrução WHILE é utilizada quando não sabemos quantas vezes um determinado bloco de instruções precisa ser repetido. Com ele, a execução das instruções vai continuar até que uma condição seja verdadeira.\n\n  DO/WHILE:A instrução DO/WHILE tem quase o mesmo funcionamento que o WHILE, a diferença é que com o uso dele teremos os comandos executados ao menos uma única vez\n\n  FOR:\n\nA instrução FOR é utilizada para executar um conjunto de comandos executado por um número X de vezes. É passada uma situação inicial, uma condição e uma ação a ser executada a cada repetição\n\n";

  static var des4 = 
    "O que são Listas?\n\nUma lista ou sequência é uma estrutura de dados abstrata que implementa uma coleção ordenada de valores, onde o mesmo valor pode ocorrer mais de uma vez.\n\nO que são Arrays?\n\nEm programação, um array que também pode ser conhecido como arranjo, é uma estrutura de dados que armazena uma coleção de elementos de tal forma que cada um dos elementos possa ser identificado por, pelo menos, um índice ou uma chave.";

  static var des5 = 
    "Uma função é um pedaço de código que faz alguma tarefa específica e pode ser chamado de qualquer parte do programa quantas vezes desejarmos.\nUtilizamos funções para obter:\n\n  •	Clareza do código: separando pedaços de código da função main(), podemos entender mais facilmente o que cada parte do código faz. Além disso, para procurarmos por uma certa ação feita pelo programa, basta buscar a função correspondente. Isso torna muito mais fácil o ato de procurar por erros.\n  •	Reutilização: muitas vezes queremos executar uma certa tarefa várias vezes ao longo do programa. Repetir todo o código para essa operação é muito trabalhoso, e torna mais difícil a manutenção do código: se acharmos um erro nesse código, teremos que corrigi-lo em todas as repetições do código. Chamar uma função diversas vezes contorna esses dois problemas.\n  •	Independência: uma função é relativamente independente do código que a chamou. Uma função pode modificar variáveis globais ou ponteiros, mas limitando-se aos dados fornecidos pela chamada de função.\n\nO princípio de uma função está, naturalmente, em permitir encapsular uma ideia ou operação, dando-lhe um nome, e então chamar essa operação de várias partes do resto de seu programa simplesmente usando o seu nome.";
}
